# Generated by Django 4.2.2 on 2023-07-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_contactme_myinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_provider_name', models.CharField(max_length=150)),
                ('profile_pic', models.CharField(max_length=150)),
                ('review_text', models.CharField(max_length=255)),
            ],
        ),
    ]
